# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default_twitter: &default_twitter
  twittet_api_key: 'T1rqQjmsDQpST7mmKFLexTDQr'
  twittet_api_secret: 'ObMHJIu7O0WUl0UnLADn7mnWhQcra8MPaGl1eIBrO52bNGAMro'

development:
  secret_key_base: 81ee578bf700716a6840d81b018ec1f771f3fe2f4cccea8dc7c0e918487f60bfc99ede6f139cebd2673a941752e3455395337c5c8ebc330f69cc4acc2c6f0e05
  <<: *default_twitter

test:
  secret_key_base: 81ee578bf700716a6840d81b018ec1f771f3fe2f4cccea8dc7c0e918487f60bfc99ede6f139cebd2673a941752e3455395337c5c8ebc330f69cc4acc2c6f0e05
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 81ee578bf700716a6840d81b018ec1f771f3fe2f4cccea8dc7c0e918487f60bfc99ede6f139cebd2673a941752e3455395337c5c8ebc330f69cc4acc2c6f0e05
  twittet_api_key: T1rqQjmsDQpST7mmKFLexTDQr
  twittet_api_secret: ObMHJIu7O0WUl0UnLADn7mnWhQcra8MPaGl1eIBrO52bNGAMro

